/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AvaPayBatchPayroll__factory } from "./AvaPayBatchPayroll__factory";
export { IERC20__factory } from "./IERC20__factory";
